Random.random

In [36]:
import random

# Returno a random float number between 0 and 1
a = random.random()
print(a)
# Return a random float number between 1 and 10
a = random.uniform(1, 10)
print(a)
# Return a random integer number between 1 and 10
a = random.randint(1, 10)
print(a)
# Other Random Functions
# Using standard normal distribution
a = random.normalvariate(0, 1)
print(a)

0.3459958169439632
4.269049229183962
6


In [113]:
# random choice
a = random.choice([1, 2, 3, 4, 5])
print(a)
# pick a random sample from a list with 3 elements
a = random.sample([1, 2, 3, 4, 5], 3)
print(a)
a = random.choices([1, 2, 3, 4, 5], k=3)
print(a)
# Shuffle a list
a = [1, 2, 3, 4, 5]
random.shuffle(a)
print(a)

4
[4, 1, 5]
[5, 5, 4]
[3, 1, 5, 4, 2]


Using seed

In [115]:
random.seed(1)
print(random.random())
print(random.randint(1, 10))
random.seed(1)
print(random.random())
print(random.randint(1, 10))
random.seed(5)
print(random.random())
print(random.randint(1, 10))

0.13436424411240122
2
0.13436424411240122
2
0.6229016948897019
6


Secrets

In [149]:
import secrets
# create real random numbers
print(secrets.randbelow(10)) # Return a int number between 0 and 9
# Return a ranidm int numver with maximum 10 bits lenght
print(secrets.randbits(10))
# Secret choice
my_list = [1, 2, 3, 4, 5]
print(secrets.choice(my_list))

2
471
3


NumPy

In [201]:
import numpy as np
# Using numpy to generate random numbers
a = np.random.rand(5, 4)
print(a)
a = np.random.randint(1, 10, size=(4, 5))
print(a)
# Shuffle a numpy array
np.random.shuffle(a)
print(a)

[[0.40106418 0.80829673 0.88241638 0.50408404]
 [0.79790809 0.65198805 0.97350525 0.27952262]
 [0.9707145  0.5385308  0.67476927 0.37539264]
 [0.36156235 0.36838017 0.45852029 0.67511177]
 [0.45836743 0.73004925 0.01826768 0.06150425]]
[[6 7 6 2 8]
 [8 5 4 1 8]
 [7 2 2 5 9]
 [5 2 8 2 5]]
[[8 5 4 1 8]
 [6 7 6 2 8]
 [7 2 2 5 9]
 [5 2 8 2 5]]


In [205]:
# Using seed
np.random.seed(1)
print(np.random.rand(5, 4))
np.random.seed(1)
print(np.random.rand(5, 4))
np.random.seed(1)
print(np.random.rand(5, 4))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01]
 [4.17304802e-01 5.58689828e-01 1.40386939e-01 1.98101489e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01]
 [4.17304802e-01 5.58689828e-01 1.40386939e-01 1.98101489e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01]
 [4.17304802e-01 5.58689828e-01 1.40386939e-01 1.98101489e-01]]
